In [1]:
import torch

### create pytorch tensors

In [3]:
# zero dimensional tensor
tensor0d = torch.tensor(1)
print(tensor0d)

tensor(1)


In [4]:
# one dimensional tensor
tensor1d = torch.tensor([1,2,3])
print(tensor1d)

tensor([1, 2, 3])


In [5]:
# two dimensional tensor
tensor2d = torch.tensor([[1,2],
                        [3,4]])
print(tensor2d)

tensor([[1, 2],
        [3, 4]])


In [7]:
# three dimensional tensor
tensor3d = torch.tensor([[[1,2], [3,4]],
                        [[5,6], [7,8]]])
print(tensor3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### tensor data types

In [ ]:
# 64-bit int
print(tensor1d.dtype)

torch.int64


In [9]:
# 32-bit precision
floatvec = torch.tensor([2.0, 3.5])
print(floatvec.dtype)

torch.float32


Trade off bw 64-bit int and 32-bit precision is precision and computational efficiency. 32-bit floating bit number uses less memory and computational resources without sacrificing much precision. Additionally, GPU archs are optimized for 32-bit computations, which results in faster model training and inference.

In [11]:
# change tensors precision
floatvec_1d_transform = tensor1d.to(torch.float32)
print(floatvec_1d_transform.dtype)

torch.float32


### common pytorch tensor operations

In [15]:
tensor2d_2 = torch.tensor([[1,2,3],
                           [4,5,6]])
print("tensor: \n", tensor2d_2)
print("tensor shape: \n", tensor2d_2.shape)

tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
tensor shape: 
 torch.Size([2, 3])


In [ ]:
# reshape tensor
print(tensor2d_2.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [17]:
# transpose tensor
print(tensor2d_2.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [18]:
# multipy two matrices
print(tensor2d_2.matmul(tensor2d_2.T))

tensor([[14, 32],
        [32, 77]])


In [19]:
# alternative, compact method to multipy two matrices
print(tensor2d_2 @ tensor2d_2.T)

tensor([[14, 32],
        [32, 77]])
