In [1]:
import numpy as np

In [2]:
def generator(z, W, b):
    """
    Returns: np.ndarray of shape (batch, output_dim) with tanh-activated values rounded to 4 decimals
    """
    z = np.asarray(z, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)

    return np.round(np.tanh(z @ W + b), 4)

#### test case #1

Input: z = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]], W = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]], b = [0.1, -0.1, 0.0, 0.2]

Output: [[0.537, -0.2913, -0.3799, 0.8005], [0.1974, 0.0997, 0.2449, 0.3364]]

In [3]:
z1 = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]]
W1 = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]]
b1 = [0.1, -0.1, 0.0, 0.2]

generator1 = generator(z=z1, W=W1, b=b1)
generator1

array([[ 0.537 , -0.2913, -0.3799,  0.8005],
       [ 0.1974,  0.0997,  0.2449,  0.3364]])

#### test case #2

Input: z = [[2.0, -1.0]], W = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]], b = [0.0, 0.1, -0.1]

Output: [[0.8005, -0.6044, -0.0997]]

In [4]:
z2 = [[2.0, -1.0]]
W2 = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]]
b2 = [0.0, 0.1, -0.1]

generator2 = generator(z=z2, W=W2, b=b2)
generator2

array([[ 0.8005, -0.6044, -0.0997]])

#### test case #3

Input: z = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]], W = [[0.4, 0.3], [-0.2, 0.5]], b = [0.1, -0.1]

Output: [[0.3799, -0.1974], [0.2913, 0.6044], [-0.2913, -0.3799]]

In [5]:
z3 = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]]
W3 = [[0.4, 0.3], [-0.2, 0.5]]
b3 = [0.1, -0.1]

generator3 = generator(z=z3, W=W3, b=b3)
generator3

array([[ 0.3799, -0.1974],
       [ 0.2913,  0.6044],
       [-0.2913, -0.3799]])

In [6]:
def discriminator(x, W):
    """
    Returns: np.ndarray of shape (batch, 1) with probabilities rounded to 4 decimals
    """
    x = np.asarray(x, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    logits = x @ W
    return np.round(1 / (1 + np.exp(-(logits))),4)

#### test case #1

Input: x = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]], W = [[0.8], [-0.3]]

Output: [[0.69], [0.4256], [0.5622]]

In [7]:
x1 = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]]
W1 = [[0.8], [-0.3]]

discriminator1 = discriminator(x=x1, W=W1)
discriminator1

array([[0.69  ],
       [0.4256],
       [0.5622]])

#### test case #2

Input: x = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]], W = [[0.5], [0.2], [-0.3]]

Output: [[0.5987], [0.4013]]

In [8]:
x2 = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]]
W2 = [[0.5], [0.2], [-0.3]]

discriminator2 = discriminator(x=x2, W=W2)
discriminator2

array([[0.5987],
       [0.4013]])

#### test case #3

Input: x = [[0.3, -0.7, 0.5, 0.1]], W = [[0.4], [-0.2], [0.6], [0.1]]

Output: [[0.6388]]

In [9]:
x3 = [[0.3, -0.7, 0.5, 0.1]]
W3 = [[0.4], [-0.2], [0.6], [0.1]]

discriminator3 = discriminator(x=x3, W=W3)
discriminator3

array([[0.6388]])

In [17]:
def discriminator_loss(real_probs, fake_probs):
    """Compute discriminator loss using binary cross-entropy.
    Returns: Loss value rounded to 4 decimals."""
    CLIPPED_LVL = 1e-8 
    real_probs = np.clip(np.asarray(real_probs, dtype=np.float64), CLIPPED_LVL, 1-CLIPPED_LVL)
    fake_probs = np.clip(np.asarray(fake_probs, dtype=np.float64), CLIPPED_LVL, 1-CLIPPED_LVL)

    return np.round(-np.mean(np.log(real_probs) + np.log(1-fake_probs)),4)

In [18]:
def generator_loss(fake_probs):
    """Compute non-saturating generator loss.
    Returns: Loss value rounded to 4 decimals."""
    CLIPPED_LVL = 1e-8 
    fake_probs = np.clip(np.asarray(fake_probs, dtype=np.float64), CLIPPED_LVL, 1-CLIPPED_LVL)

    return np.round(-np.mean(np.log(fake_probs)),4)

#### test case #1

Input: real_probs = [0.9, 0.95], fake_probs = [0.1, 0.05]

Output: 0.1567

In [19]:
real_probs1 = [0.9, 0.95]
fake_probs1 = [0.1, 0.05]

discriminator_loss1 = discriminator_loss(real_probs=real_probs1, fake_probs=fake_probs1)
print(f"discriminator_loss1 = {discriminator_loss1}")
generator_loss1 = generator_loss(fake_probs=fake_probs1)
print(f"generator_loss1 = {generator_loss1}")

discriminator_loss1 = 0.1567
generator_loss1 = 2.6492


#### test case #2

Input: real_probs = [0.5, 0.5], fake_probs = [0.5, 0.5]

Output: 1.3863

In [20]:
real_probs2 = [0.5, 0.5]
fake_probs2 = [0.5, 0.5]

discriminator_loss2 = discriminator_loss(real_probs=real_probs2, fake_probs=fake_probs2)
print(f"discriminator_loss2 = {discriminator_loss2}")
generator_loss2 = generator_loss(fake_probs=fake_probs2)
print(f"generator_loss2 = {generator_loss2}")

discriminator_loss2 = 1.3863
generator_loss2 = 0.6931


#### test case #3

Input: real_probs = [0.99, 0.98, 0.97], fake_probs = [0.01, 0.02, 0.03]

Output: 0.0405

In [21]:
real_probs3 = [0.99, 0.98, 0.97]
fake_probs3 = [0.01, 0.02, 0.03]

discriminator_loss3 = discriminator_loss(real_probs=real_probs3, fake_probs=fake_probs3)
print(f"discriminator_loss3 = {discriminator_loss3}")
generator_loss3 = generator_loss(fake_probs=fake_probs3)
print(f"generator_loss3 = {generator_loss3}")

discriminator_loss3 = 0.0405
generator_loss3 = 4.0079


In [22]:
def train_gan_step(real_data, fake_data, D_W):
    """
    Returns: dict with "d_loss" and "g_loss" as float values
    """
    EPSILON = 1e-8
    
    real_data = np.asarray(real_data, dtype=np.float64)
    fake_data = np.asarray(fake_data, dtype=np.float64)
    D_W = np.asarray(D_W, dtype=np.float64)

    p_real = np.clip(1 / (1 + np.exp(-real_data@D_W)), EPSILON, 1-EPSILON)
    p_fake = np.clip(1 / (1 + np.exp(-fake_data@D_W)), EPSILON, 1-EPSILON)

    d_loss = -np.mean(np.log(p_real) + np.log(1-p_fake))
    g_loss = -np.mean(np.log(p_fake))

    return {'d_loss': np.round(d_loss, 4), 'g_loss': np.round(g_loss, 4)}

#### test case #1

Input: real_data = [[1.0, 0.5, -0.3], [0.8, -0.2, 0.6]], fake_data = [[-0.5, 0.3, 0.1], [0.2, -0.8, 0.4]], D_W = [[0.5], [-0.3], [0.2]]

Output: {"d_loss": 1.2371, "g_loss": 0.6855}

In [23]:
real_data1 = [[1.0, 0.5, -0.3], [0.8, -0.2, 0.6]]
fake_data1 = [[-0.5, 0.3, 0.1], [0.2, -0.8, 0.4]]
D_W1 = [[0.5], [-0.3], [0.2]]

train_gan_step1 = train_gan_step(real_data=real_data1, fake_data=fake_data1, D_W=D_W1)
train_gan_step1

{'d_loss': np.float64(1.2371), 'g_loss': np.float64(0.6855)}

#### test case #2

Input: real_data = [[2.0, 1.0], [1.5, 0.8]], fake_data = [[-2.0, -1.0], [-1.5, -0.8]], D_W = [[1.0], [0.5]]

Output: {"d_loss": 0.2183, "g_loss": 2.3091}

In [24]:
real_data2 = [[2.0, 1.0], [1.5, 0.8]]
fake_data2 = [[-2.0, -1.0], [-1.5, -0.8]]
D_W2 = [[1.0], [0.5]]

train_gan_step2 = train_gan_step(real_data=real_data2, fake_data=fake_data2, D_W=D_W2)
train_gan_step2

{'d_loss': np.float64(0.2183), 'g_loss': np.float64(2.3091)}

#### test case #3

Input: real_data = [[0.3, -0.7]], fake_data = [[0.5, 0.2]], D_W = [[0.4], [-0.6]]

Output: {"d_loss": 1.1931, "g_loss": 0.6539}

In [25]:
real_data3 = [[0.3, -0.7]]
fake_data3 = [[0.5, 0.2]]
D_W3 = [[0.4], [-0.6]]

train_gan_step3 = train_gan_step(real_data=real_data3, fake_data=fake_data3, D_W=D_W3)
train_gan_step3

{'d_loss': np.float64(1.1931), 'g_loss': np.float64(0.6539)}

In [26]:
def detect_mode_collapse(generated_samples, threshold=0.1):
    """
    Returns: dict with "diversity_score" (float) and "is_collapsed" (bool)
    """
    generated_samples = np.asarray(generated_samples, dtype=np.float64)
    diversity_score = np.mean(np.std(generated_samples, axis=0))
    is_collapsed = diversity_score < threshold

    return {"diversity_score": float(np.round(diversity_score, 4)), "is_collapsed": bool(is_collapsed)}

#### test case #1

Input: generated_samples = [[1.0, 2.0, 3.0], [1.0, 2.0, 3.0], [1.0, 2.0, 3.0]], threshold = 0.1

Output: {"diversity_score": 0.0, "is_collapsed": true}

In [27]:
generated_samples1 = [[1.0, 2.0, 3.0], [1.0, 2.0, 3.0], [1.0, 2.0, 3.0]]
threshold1 = 0.1

detect_mode_collapse1 = detect_mode_collapse(generated_samples=generated_samples1, threshold=threshold1)
detect_mode_collapse1

{'diversity_score': 0.0, 'is_collapsed': True}

#### test case #2

Input: generated_samples = [[1.0, 0.0], [-1.0, 2.0], [0.5, -1.5], [2.0, 1.0], [-0.5, 0.5]], threshold = 0.1

Output: {"diversity_score": 1.1126, "is_collapsed": false}

In [28]:
generated_samples2 = [[1.0, 0.0], [-1.0, 2.0], [0.5, -1.5], [2.0, 1.0], [-0.5, 0.5]]
threshold2 = 0.1

detect_mode_collapse2 = detect_mode_collapse(generated_samples=generated_samples2, threshold=threshold2)
detect_mode_collapse2

{'diversity_score': 1.1126, 'is_collapsed': False}

#### test case #3

Input: generated_samples = [[1.0, 2.0], [1.01, 2.02], [0.99, 1.98], [1.0, 2.01]], threshold = 0.1

Output: {"diversity_score": 0.0109, "is_collapsed": true}

In [29]:
generated_samples3 = [[1.0, 2.0], [1.01, 2.02], [0.99, 1.98], [1.0, 2.01]]
threshold3 = 0.1

detect_mode_collapse3 = detect_mode_collapse(generated_samples=generated_samples3, threshold=threshold3)
detect_mode_collapse3

{'diversity_score': 0.0109, 'is_collapsed': True}