In [1]:
import numpy as np

In [2]:
def generator(z, W, b):
    """
    Returns: np.ndarray of shape (batch, output_dim) with tanh-activated values rounded to 4 decimals
    """
    z = np.asarray(z, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)

    return np.round(np.tanh(z @ W + b), 4)

#### test case #1

Input: z = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]], W = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]], b = [0.1, -0.1, 0.0, 0.2]

Output: [[0.537, -0.2913, -0.3799, 0.8005], [0.1974, 0.0997, 0.2449, 0.3364]]

In [3]:
z1 = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]]
W1 = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]]
b1 = [0.1, -0.1, 0.0, 0.2]

generator1 = generator(z=z1, W=W1, b=b1)
generator1

array([[ 0.537 , -0.2913, -0.3799,  0.8005],
       [ 0.1974,  0.0997,  0.2449,  0.3364]])

#### test case #2

Input: z = [[2.0, -1.0]], W = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]], b = [0.0, 0.1, -0.1]

Output: [[0.8005, -0.6044, -0.0997]]

In [4]:
z2 = [[2.0, -1.0]]
W2 = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]]
b2 = [0.0, 0.1, -0.1]

generator2 = generator(z=z2, W=W2, b=b2)
generator2

array([[ 0.8005, -0.6044, -0.0997]])

#### test case #3

Input: z = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]], W = [[0.4, 0.3], [-0.2, 0.5]], b = [0.1, -0.1]

Output: [[0.3799, -0.1974], [0.2913, 0.6044], [-0.2913, -0.3799]]

In [5]:
z3 = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]]
W3 = [[0.4, 0.3], [-0.2, 0.5]]
b3 = [0.1, -0.1]

generator3 = generator(z=z3, W=W3, b=b3)
generator3

array([[ 0.3799, -0.1974],
       [ 0.2913,  0.6044],
       [-0.2913, -0.3799]])

In [6]:
def discriminator(x, W):
    """
    Returns: np.ndarray of shape (batch, 1) with probabilities rounded to 4 decimals
    """
    x = np.asarray(x, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    logits = x @ W
    return np.round(1 / (1 + np.exp(-(logits))),4)

#### test case #1

Input: x = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]], W = [[0.8], [-0.3]]

Output: [[0.69], [0.4256], [0.5622]]

In [7]:
x1 = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]]
W1 = [[0.8], [-0.3]]

discriminator1 = discriminator(x=x1, W=W1)
discriminator1

array([[0.69  ],
       [0.4256],
       [0.5622]])

#### test case #2

Input: x = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]], W = [[0.5], [0.2], [-0.3]]

Output: [[0.5987], [0.4013]]

In [8]:
x2 = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]]
W2 = [[0.5], [0.2], [-0.3]]

discriminator2 = discriminator(x=x2, W=W2)
discriminator2

array([[0.5987],
       [0.4013]])

#### test case #3

Input: x = [[0.3, -0.7, 0.5, 0.1]], W = [[0.4], [-0.2], [0.6], [0.1]]

Output: [[0.6388]]

In [9]:
x3 = [[0.3, -0.7, 0.5, 0.1]]
W3 = [[0.4], [-0.2], [0.6], [0.1]]

discriminator3 = discriminator(x=x3, W=W3)
discriminator3

array([[0.6388]])

In [ ]:
def discriminator_loss(real_probs, fake_probs):
    """Compute discriminator loss using binary cross-entropy.
    Returns: Loss value rounded to 4 decimals."""
    real_probs = np.asarray(real_probs, dtype=np.float64)
    fake_probs = np.asarray(fake_probs, dtype=np.float64)

    return np.round(-np.mean(np.log(real_probs) + np.log(1-fake_probs)),4)

In [ ]:
def generator_loss(fake_probs):
    """Compute non-saturating generator loss.
    Returns: Loss value rounded to 4 decimals."""
    fake_probs = np.asarray(fake_probs, dtype=np.float64)

    return np.round(-np.mean(np.log(fake_probs)),4)

#### test case #1

Input: real_probs = [0.9, 0.95], fake_probs = [0.1, 0.05]

Output: 0.1567

In [12]:
real_probs1 = [0.9, 0.95]
fake_probs1 = [0.1, 0.05]

discriminator_loss1 = discriminator_loss(real_probs=real_probs1, fake_probs=fake_probs1)
print(f"discriminator_loss1 = {discriminator_loss1}")
generator_loss1 = generator_loss(fake_probs=fake_probs1)
print(f"generator_loss1 = {generator_loss1}")

discriminator_loss1 = 0.15665381004537687
generator_loss1 = 2.649158683274018


#### test case #2

Input: real_probs = [0.5, 0.5], fake_probs = [0.5, 0.5]

Output: 1.3863

In [13]:
real_probs2 = [0.5, 0.5]
fake_probs2 = [0.5, 0.5]

discriminator_loss2 = discriminator_loss(real_probs=real_probs2, fake_probs=fake_probs2)
print(f"discriminator_loss2 = {discriminator_loss2}")
generator_loss2 = generator_loss(fake_probs=fake_probs2)
print(f"generator_loss2 = {generator_loss2}")

discriminator_loss2 = 1.3862943611198906
generator_loss2 = 0.6931471805599453


#### test case #3

Input: real_probs = [0.99, 0.98, 0.97], fake_probs = [0.01, 0.02, 0.03]

Output: 0.0405

In [14]:
real_probs3 = [0.99, 0.98, 0.97]
fake_probs3 = [0.01, 0.02, 0.03]

discriminator_loss3 = discriminator_loss(real_probs=real_probs3, fake_probs=fake_probs3)
print(f"discriminator_loss3 = {discriminator_loss3}")
generator_loss3 = generator_loss(fake_probs=fake_probs3)
print(f"generator_loss3 = {generator_loss3}")

discriminator_loss3 = 0.04047483377048633
generator_loss3 = 4.007917029578739
