In [2]:
import numpy as np

In [3]:
def generator(z, W, b):
    """
    Returns: np.ndarray of shape (batch, output_dim) with tanh-activated values rounded to 4 decimals
    """
    z = np.asarray(z, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)

    return np.round(np.tanh(z @ W + b), 4)

#### test case #1

Input: z = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]], W = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]], b = [0.1, -0.1, 0.0, 0.2]

Output: [[0.537, -0.2913, -0.3799, 0.8005], [0.1974, 0.0997, 0.2449, 0.3364]]

In [4]:
z1 = [[1.0, 0.0, -1.0], [0.5, 0.5, 0.5]]
W1 = [[0.3, -0.1, 0.2, 0.5], [0.1, 0.4, -0.3, 0.2], [-0.2, 0.1, 0.6, -0.4]]
b1 = [0.1, -0.1, 0.0, 0.2]

generator1 = generator(z=z1, W=W1, b=b1)
generator1

array([[ 0.537 , -0.2913, -0.3799,  0.8005],
       [ 0.1974,  0.0997,  0.2449,  0.3364]])

#### test case #2

Input: z = [[2.0, -1.0]], W = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]], b = [0.0, 0.1, -0.1]

Output: [[0.8005, -0.6044, -0.0997]]

In [5]:
z2 = [[2.0, -1.0]]
W2 = [[0.5, -0.2, 0.3], [-0.1, 0.4, 0.6]]
b2 = [0.0, 0.1, -0.1]

generator2 = generator(z=z2, W=W2, b=b2)
generator2

array([[ 0.8005, -0.6044, -0.0997]])

#### test case #3

Input: z = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]], W = [[0.4, 0.3], [-0.2, 0.5]], b = [0.1, -0.1]

Output: [[0.3799, -0.1974], [0.2913, 0.6044], [-0.2913, -0.3799]]

In [6]:
z3 = [[0.5, -0.5], [1.0, 1.0], [-1.0, 0.0]]
W3 = [[0.4, 0.3], [-0.2, 0.5]]
b3 = [0.1, -0.1]

generator3 = generator(z=z3, W=W3, b=b3)
generator3

array([[ 0.3799, -0.1974],
       [ 0.2913,  0.6044],
       [-0.2913, -0.3799]])

In [7]:
def discriminator(x, W):
    """
    Returns: np.ndarray of shape (batch, 1) with probabilities rounded to 4 decimals
    """
    x = np.asarray(x, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    logits = x @ W
    return np.round(1 / (1 + np.exp(-(logits))),4)

#### test case #1

Input: x = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]], W = [[0.8], [-0.3]]

Output: [[0.69], [0.4256], [0.5622]]

In [8]:
x1 = [[1.0, 0.0], [0.0, 1.0], [0.5, 0.5]]
W1 = [[0.8], [-0.3]]

discriminator1 = discriminator(x=x1, W=W1)
discriminator1

array([[0.69  ],
       [0.4256],
       [0.5622]])

#### test case #2

Input: x = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]], W = [[0.5], [0.2], [-0.3]]

Output: [[0.5987], [0.4013]]

In [10]:
x2 = [[1.0, 1.0, 1.0], [-1.0, -1.0, -1.0]]
W2 = [[0.5], [0.2], [-0.3]]

discriminator2 = discriminator(x=x2, W=W2)
discriminator2

array([[0.5987],
       [0.4013]])

#### test case #3

Input: x = [[0.3, -0.7, 0.5, 0.1]], W = [[0.4], [-0.2], [0.6], [0.1]]

Output: [[0.6388]]

In [11]:
x3 = [[0.3, -0.7, 0.5, 0.1]]
W3 = [[0.4], [-0.2], [0.6], [0.1]]

discriminator3 = discriminator(x=x3, W=W3)
discriminator3

array([[0.6388]])