In [1]:
import pandas as pd
import numpy as np

In [ ]:
random_data = np.random.sample((1000,2))
random_data[:5]

array([[0.80096494, 0.11113531],
       [0.46760805, 0.22020196],
       [0.22753273, 0.49352174],
       [0.34270272, 0.96479576],
       [0.0542636 , 0.47173999]])

In [ ]:
random_data

array([], shape=(0, 2), dtype=float64)

In [17]:
random_w = np.random.sample((1))
random_w[:5]

array([0.9544488])

In [28]:
# w_i <-- w_i + n(t-o) * x_i
o = random_data[:, 0] * random_w.T
o[:5]

array([0.76448003, 0.44630794, 0.21716834, 0.3270922 , 0.05179183])

In [27]:
t = random_data[:, 1]
t[:5]

array([0.11113531, 0.22020196, 0.49352174, 0.96479576, 0.47173999])

In [38]:
# loop for SGD
def sgd_loop(data, weights, lr=0.05, loops=10):
    for n in range(loops):
        weights = weights + lr * (data[n, 1] - (data[n, 0] * weights)) * data[n, 0]
    return weights

In [39]:
wi = sgd_loop(random_data, random_w)
wi

array([0.93127997])